server:
  servlet:
    context-path: /matchboxv3
hapi:
  fhir:
    server_address: http://localhost:8080/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_terminology:
        name: hl7.terminology.r4
        version: 6.1.0
        url: classpath:/hl7.terminology.r4#6.1.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions.r4#1.0.0.tgz
      hl7_fhir_uv_ips:
        name: ch.fhir.ig.ch-alis
        version: 0.2.0
        url: file:/Users/oegger/Documents/github/ch-alis/output/package.tgz
    staticLocation: file:/apps/
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
      onlyOneEngine: true
spring:
  datasource:
    url: "jdbc:h2:mem:test"
