server:
  servlet:
    context-path: /matchboxv3
hapi:
  fhir:
#    server_address: http://localhost:8080/matchboxv3/fhir
    server_address: http://localhost:18002/eprik-fhir/camel/matchbox/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_terminology:
        name: hl7.terminology.r4
        version: 6.1.0
        url: classpath:/hl7.terminology.r4#6.1.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions.r4#1.0.0.tgz
      hl7_fhir_uv_ips:
        name: hl7.fhir.uv.ips
        version: current
        url: file:/Users/oegger/Documents/github/fhir-ips/output/package.tgz
      fhir_eu_lab:
        name: hl7.fhir.eu.laboratory
        version: current
        url: file:/Users/oegger/Documents/github/laboratory-1/output/package.tgz
      ch_core:
        name: ch.fhir.ig.ch-core
        version: current
        url: file:/Users/oegger/Documents/github/ch-core/output/package.tgz
      fhir_ch_lab:
        name: ch.fhir.ig.ch-lab-report
        version: current
        url: file:/Users/oegger/Documents/github/ch-lab-report/output/package.tgz
      ch_elm:
        name: ch.fhir.ig.ch-elm
        version: 1.0.0-ci-build
        url: file:/Users/oegger/Documents/github/ch-elm/output/package.tgz
    staticLocation: file:/apps/
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
#      txServer: http://tx.fhir.org
      txServer: http://localhost:18002/eprik-fhir/camel/tx/r4/
      onlyOneEngine: true
