name: Integration tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout matchbox
        uses: actions/checkout@v3
        with:
          path: matchbox

      - name: Checkout integration tests
        uses: actions/checkout@v3
        with:
          path: matchbox-int-tests
          repository: ahdis/matchbox-int-tests

      - name: Setup Java 21
        uses: actions/setup-java@v3
        # https://github.com/actions/setup-java#usage
        with:
          java-version: 21
          distribution: adopt
          cache: maven

      - name: Install matchbox locally
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -DskipTests -P !boot install
        working-directory: matchbox

      - name: Extract matchbox version
        run: echo "MATCHBOX_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_ENV"
        working-directory: matchbox

      - name: Show matchbox version
        run: |
          echo "Version '$MATCHBOX_VERSION'"
          echo "Version '${{ env.MATCHBOX_VERSION }}'"

      - name: Run the tests
        timeout-minutes: 90 # We need a long timeout here
        env:
          MAVEN_OPTS: -Xmx12g
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -Dmatchbox.version="${{ env.MATCHBOX_VERSION }}" verify site
        working-directory: matchbox-int-tests
          
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testresults
          path: ./matchbox-int-tests/target/site
          retention-days: 2