# This workflow will test the Javadoc of a Java project with Maven
name: Javadoc test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        # https://github.com/actions/setup-java#usage
        with:
          java-version: 21
          distribution: adopt
          cache: maven

      - name: Test the Javadoc
        run: mvn --batch-mode --no-transfer-progress javadoc:aggregate -f pom.xml
